apiVersion: v1
kind: Pod
metadata:
    name: cmd-arg-demo
    labels:
        app: cmd-arg-demo
spec:
    containers:
        - name: cmd-arg-demo-container
          image: debian
          command: ["printenv"]
          args: ["HOSTNAME", "KUBERNETES_PORT"]
